### ISSUE TITLE
Vue-fontawesome icons not loading

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [vanderb/vue-badger-accordion#9]
So I am trying to use the vue-fontawesome package to add custom icons.

Now I have followed your code and setup the accordion as so

`<badger-accordion class="card mb-0" :icons="{opened: openedIcon, closed: closedIcon}">`

Then added two computed props as so

`
computed: {
  openedIcon: function () {
    return '<fa icon="angle-down" class="mr-1" fixed-width/>'
  },
  closedIcon: function () {
    return '<fa icon="angle-right" class="mr-1" fixed-width/>'
  }
}
`

Now once the page loads the fa tags are loaded in but not replaced with there SVG versions. Does any one now why this would be ?

**Comment by vanderb** [comment]
Hi, you are using font-awesome 5, right? The readme covered font-awesome 4, where the icons were implemented by css.

The problem is: This component cannot render other components from string. I will take a look into this, I am sure we can find a solution for that.

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb Yes I am using 5.

Thank you for looking into this :-)

**Comment by vanderb** [comment]
@Chris-Pratt-Clystnet I've found a solution. I will fix some other issues and publish a new version. I inform you if it's updated.

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb Thanks :-)

**Comment by vanderb** [comment]
@Chris-Pratt-Clystnet Please update to v 1.1.4. This should be fixed there. Please, can you verify this? I  then will close this issue.

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb I am still having the same issue

I am inputting the new icons as so

`<badger-accordion class="card mb-0" :icons="{opened: openedIcon, closed: closedIcon}">`

With two data entries as so

`
openedIcon: '<fa icon="angle-down" class="mr-1" fixed-width/>',
closedIcon: '<fa icon="angle-right" class="mr-1" fixed-width/>'
`

Is this the correct way to set the icons in this instance ?

**Comment by vanderb** [comment]
@Chris-Pratt-Clystnet I've tested this with the fa-package for Vue (https://www.npmjs.com/package/@fortawesome/vue-fontawesome). But thats not the point. If <fa> works in normal way, this should work in this package too.

**Comment by DragonI** [comment]
@Chris-Pratt-Clystnet, here is how I got it to work. The key / trickery is using **[dom.watch()](https://github.com/FortAwesome/vue-fontawesome#processing-i-tags-into-svg-using-font-awesome)** from vue-fontawesome and specifying the generated icon HTML - see badgerIcons

template
```
    <badger-accordion
      ref="myAccordion"
      :icons="badgerIcons"
    >
...
```
script
```
// import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome' // Not Required!

// only load what's required to minimize build size
import { faChevronDown, faChevronUp } from '@fortawesome/free-solid-svg-icons'
import { library, dom } from '@fortawesome/fontawesome-svg-core'

library.add(faChevronDown, faChevronUp)

export default {
  components: {
    BadgerAccordion,
    BadgerAccordionItem
  },

  data () {
    return {
      badgerIcons: {
        opened: '<i class="fas fa-chevron-up"></i>',
        closed: '<i class="fas fa-chevron-down"></i>'
      }
    }
  },

  mounted () {
    dom.watch() // required for open / close toggle to work
  }
}
```
@vanderb, I upgraded to 1.1.4 from 1.1.3. I reverted back because of the following.

v1.1.4 was supposed to be a bug fix but fontawesome and vue-fontawesome were included in [BadgerAccordionItem.vue](https://github.com/vanderb/vue-badger-accordion/commit/093286c672081be96d0760cf57f67db82c121f9e). They were never added as dependencies. And the <font-awesome-icon> component is never used.

```
    import Vue from 'vue'
    import { library } from '@fortawesome/fontawesome-svg-core'
    import { fas } from '@fortawesome/free-solid-svg-icons'
    import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
    library.add(fas);
    Vue.component('font-awesome-icon', FontAwesomeIcon)
```

Anyone trying to use your component will get errors if they haven't been installed.

Anyone who does have fontawesome installed will be surprised after performing a build. The free-solid-svg-icons js chunk file is **over 600K** because all of the icons were imported via "fas"

![free-solid-svg-icons chunk size](https://i.imgur.com/tD3q83s.jpg)

v1.1.4 did fix an issue with previous versions ⁠— where the 2nd badger item would momentarily display and then collapse. Tried this.$refs.myAccordion.closeAll() on mount but didn't work. 

If the next release removes fontawesome and vue-fontawesome, everything should be good.

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb I have confirmed this works with the configuration that @DragonI gave me

**Comment by vanderb** [comment]
@DragonI **Thanks** for reporting this. 
I messed this up, **sorry for that**.
@Chris-Pratt-Clystnet I removed that wrong implementation.

**Comment by DragonI** [comment]
@vanderb, np — thx for component. Tested v1.1.5 and both issues have been fixed.

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb Since the last update the icons no longer load for me and instead all I see is 
![image](https://user-images.githubusercontent.com/40233133/60655300-6c64fb00-9e45-11e9-8a22-192d44eef42b.png)

Also when looking into this I found this topic on the vue fontawesome package

https://github.com/FortAwesome/vue-fontawesome/issues/140

It seems we should not be using dom.watch() when using vue.

Now my question here is would it be possible to instead use slots to change the icon rather than a data property ?

**Comment by Human626** [comment]
@vanderb Hi, I'm getting this issue too :,( 
Any ideas as to how long it will be before the fix is out?

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb I put the code back into BadgerAccordionItem that you removed in the last patch and it works again.

Now I am loading font awesome globally as I use it all over the place so for some reason your component is ignoring my globally loaded font awesome.

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb Ok ignore on this one I was getting my icons confused, thought i was using the angle icon but was using the chevron icon.

I am going to close this ticket now as this is all working.
